##  Заголовок инструкции
#  Имя инструкции в системе github
name: Deploy

#  указываем github на какие действия нужно выполнить эту инструкцию
on:               # подпись (операцию)
  push:           # событие (отправка на сервер нового/измененного кода)
    branches: [main]    # за какой веткой кода нужно следить

##  Раздел самой инструкции - действия которые выполнить,
##  если инструкцию нужно выполнить
##  (СТРУКТУРУ ИНСТРУКЦИИ МЕНЯ НЕЛЬЗЯ)

#  Задачи этой инструкции, которые нужно выполнить github
jobs:     # раздел задач
  deployTask:               # задача по имени deployTask(название можно менять, но нельзя опустить)
    runs-on: ubuntu-latest  # на какую операционную систему ориентирована данная инструкция(нельзя менять ключ)
    steps:                  # шаги выполнения задачи (менять нельзя)
      # любой шаг начинается с '-'

      # первый шаг
      - uses: actions/checkout@v2   
      # указываем github,
      # что будем работать с кодом проекта(своим)
      # (менять нельзя и ключ и значение)

      # второй шаг - развертывание
      - name: Deploy project                  # имя шага
        uses: akhileshns/heroku-deploy@v3.4.6 # инструменты для развертывания
        with:           # Параметры для инструментов
          #  API ключ от heroku - чтобы гит смог представлять тебя от своего лица (Что ты есть ты, а не Вася)
          heroku_api_key: 65144d45-e66f-424d-ba7a-c928c4a7ca1a 
          #  Имя приложения - то, куда будет заливать наш код и развертываться сервер
          heroku_app_name: server-i-lena
          #  Email владельца сервера
          heroku_email: ovechkina.elina@yandex.ru

      # третий шаг - получение тестов от команды тестировщиков
      - name: Checkout test repository
        # инструментарий получения кода из репозитория
        uses: actions/checkout@v2
        with:
          # репозиторий, из котого нужно получить код
          repository: Elena-Ovechkina/DISP1_Tests
          # папка(директория) в которую этот код нужно разместить
          path: tests
          # ветка версионного контроля из которой нужно получить код
          ref: master

      # четвертый шаг - установка библиотек для запуска тестов
      - name: Install dependecies
        # команда установки библиотек
        run: npm install
        # относительно какой папки выполнить эту команду
        working-directory: tests

      # пятный шаг - запуск тестов относительно тестового стенда
      - name: Run test
        # команда запуска тестов
        run: npm start
        # относительно какой папки выполнить эту команду
        working-directory: tests
